# Fetch all hosts in us-west-1
plugin: amazon.aws.aws_ec2

regions:
  - us-west-1

hostnames:
  - tag:Name

# Only target hosts that are a part of this deployment group.
filters:
  tag:InventoryGroup: 'requis_backend'

# Add hosts to group based on the values of a variable.
keyed_groups:
  - key: tags['InventoryGroup']
    prefix: "group"

  - key: tags['InstanceGroup']
    prefix: "group"

# Use the public IP address to connect to the host
# (note: this does not modify inventory_hostname)
compose:
  ansible_host: public_ip_address