version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.9.6
        name: terraform
  ansible:
    docker:
      - image: alpine/ansible:2.17.0
        name: ansible

jobs:
  terraform_provision_ec2:
    executor: terraform
    working_directory: ~/project/terraform
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Terraform Version
          command: |
            terraform --version
      - run:
          name: Terraform Init
          command: |
            terraform init
      - run:
          name: Terraform Plan
          command: |
            terraform plan -var-file="vars/<< parameters.environment >>.tfvars" -var='enable_elb=false' -out << parameters.environment >>.tfplan
      - run:
          name: Apply Terraform EC2 Resources
          command: terraform apply << parameters.environment >>.tfplan

  ansible_playbook:
    executor: ansible
    working_directory: ~/project/ansible
    steps:
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i inventory/aws_ec2.yaml playbooks/health_check.yaml

  terraform_provision_autoscaling:
    executor: terraform
    working_directory: ~/project/terraform
    parameters:
      environment:
        type: string
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Terraform Version
          command: |
            terraform --version
      - run:
          name: Terraform Init
          command: |
            terraform init
      - run:
          name: Terraform Plan
          command: |
            terraform plan -var-file="vars/<< parameters.environment >>.tfvars" -var='enable_elb=true' -out << parameters.environment >>.tfplan
      - run:
          name: Apply Terraform EC2 Resources
          command: |
            terraform apply << parameters.environment >>.tfplan -var='enable_elb=true' -var='enable_elb=true' -auto-approve

workflows:
  deploy:
    jobs:
      - terraform_provision_ec2:
          context:
            - aws_deploy
          environment: development

      - ansible_playbook:
          context:
            - aws_deploy
          requires:
            - terraform_provision_ec2

      - terraform_provision_autoscaling:
          context:
            - aws_deploy
          requires:
            - ansible_playbook
          environment: development