version: 2.1

jobs:
  # The setup job builds an image with Ansible and Terraform.
  # Terraform is used to execute the ansible playbook
  # command for the ec2 instances.
  setup:
    docker:
      - image: alpine:3
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            apk add --update --no-cache ansible bash openssh sshpass
      - run:
          name: Ansible Version
          command: |
            ansible --version
      - run:
          name: Install Terraform
          command: |
            apk add --update --virtual .deps --no-cache gnupg && \
            cd /tmp && \
            wget https://releases.hashicorp.com/terraform/1.9.6/terraform_1.9.6_linux_amd64.zip && \
            wget https://releases.hashicorp.com/terraform/1.9.6/terraform_1.9.6_SHA256SUMS && \
            wget https://releases.hashicorp.com/terraform/1.9.6/terraform_1.9.6_SHA256SUMS.sig && \
            wget -qO- https://www.hashicorp.com/.well-known/pgp-key.txt | gpg --import && \
            gpg --verify terraform_1.9.6_SHA256SUMS.sig terraform_1.9.6_SHA256SUMS && \
            grep terraform_1.9.6_linux_amd64.zip terraform_1.9.6_SHA256SUMS | sha256sum -c && \
            unzip /tmp/terraform_1.9.6_linux_amd64.zip -d /tmp && \
            mv /tmp/terraform /usr/local/bin/terraform && \
            rm -f /tmp/terraform_1.9.6_linux_amd64.zip terraform_1.9.6_SHA256SUMS 1.9.6/terraform_1.9.6_SHA256SUMS.sig && \
            apk del .deps
      - run:
          name: Terraform Version
          command: terraform -v
      - run:
          name: List Directory
          command: ls .
      - run:
          name: Initialize Terraform
          command: terraform -chdir="terraform" init
      - run:
          name: Terraform Plan
          command: |
            terraform -chdir="terraform" plan -var-file=./vars/development.tfvars -out development.tfplan
      - run:
          name: Terraform Apply
          command: |
            terraform -chdir="terraform" apply
      - run:
          name: Terraform Destroy
          command: |
            terraform -chdir="terraform" apply -destroy -var-file="vars/development.tfvars"

workflows:
  deploy:
    jobs:
      - setup