version: 2.1

jobs:
  setup:
    docker:
      - image: alpine/ansible:2.17.0
      - image: hashicorp/terraform:1.10
    steps:
      - checkout
      - run:
          name: Terraform Version
          command: |
            terraform -v
      - run:
          name: Ansible Version
          command: |
            ansible --version
            
workflows:
  deploy:
    jobs:
      - setup