version: 2.1

jobs:
  # Run ansible and ansible-playbook in docker.
  ansible-control-node:
    docker:
      - image: alpine/ansible:2.17.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false # TODO: add flag for docker layer caching

workflows:
  deploy:
    jobs:
      # The ansible control node is started asynchronously and must be awaited on.
      - ansible-control-node