version: 2.1

jobs:
  ansible:
    docker:
      - image: alpine/ansible:2.17.0
        name: ansible
    steps:
      - checkout
      - run:
          name: Ansible Version
          command: |
            ansible --version
  terraform:
    docker:
      - image: hashicorp/terraform:1.10
        name: terraform
    steps:
      - checkout
      - run:
          name: Terraform Version
          command: |
            terraform --version
      - run:
          name: Install Docker
          command: |
            apk add docker
      - run:
          name: Ansible Controller
          command: |
            docker inspect -f ‘{{range.NetworkSettings. Networks}}{{.IPAddress}}{{end}}’ ansible

workflows:
  deploy:
    jobs:
      - ansible:
          context:
            - aws_deploy
      - terraform:
          context:
            - aws_deploy
          requires:
            - ansible