version: 2.1

jobs:
  ansible:
    docker:
      - image: alpine/ansible:2.17.0
    steps:
      - checkout
      - run:
          name: Ansible Version
          command: |
            ansible --version
      # Generate an ssh key and persist to the workspace so that
      # the terraform container can ssh into the ansible
      # container.
      - run:
          name: Generate SSH Key
          command: ssh-keygen -t rsa -b 4096 -C "job-a-to-job-b" -f ~/.ssh/id_rsa -N ""
      - persist_to_workspace:
          root: ~/.ssh
          paths:
            - id_rsa
            - id_rsa.pub
    
  terraform-plan:
    docker:
      - image: hashicorp/terraform:1.10
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Setup SSH Server
          command: |
            apt-get update && apt-get install -y openssh-server
            mkdir -p ~/.ssh
            mv /workspace/id_rsa.pub ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            /usr/sbin/sshd
      - run:
          name: Terraform Version
          command: |
            terraform --version
            

workflows:
  deploy:
    jobs:
      - ansible:
          context:
            - aws_deploy
      - terraform-plan:
          context:
            - aws_deploy