version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.9.6
        name: terraform
  ansible:
    docker:
      - image: alpine/ansible:2.17.0
        name: ansible

jobs:
  terraform_provision_ec2:
    executor: terraform
    working_directory: ~/project/terraform
    parameters:
      environment:
        type: string
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Terraform Version
          command: |
            terraform --version
      - run:
          name: Terraform Init
          command: |
            terraform init
      - run:
          name: Terraform Plan
          command: |
            terraform plan -var-file="vars/<< parameters.environment >>.tfvars" -out << parameters.environment >>.tfplan
      - run:
          name: Terraform Apply
          command: |
            terraform apply << parameters.environment >>.tfplan

  ansible_playbook:
    executor: ansible
    working_directory: ~/project/ansible
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/local/bin/python3
    steps:
      - checkout:
          path: ~/project

      - add_ssh_keys

      - run:
          name: Ansible Version
          command: |
            ansible --version

      - run:
          name: Ansible Playbook Version
          command: |
            ansible-playbook --version

      - run:
          name: Install boto3 and botocore
          command: |
            /usr/local/bin/python3 -m pip install boto3 botocore --user ansible

      - run:
          name: Save Ansible SSH Key
          command: |
            echo "$AWS_INSTANCE_PRIVATE_KEY" | base64 --decode > ansible-private-key.pem
            chmod 400 ansible-private-key.pem

      - run:
          name: Print Key
          command: |
            cat ansible-private-key.pem
  
      - run:
          name: List Directory Contents
          command: |
            ls .

      - run:
          name: List ansible EC2 inventory
          command: |
            ansible-inventory -i ./inventory/aws_ec2.yaml --list

      - run:
          name: Deploy EC2 instance with playbook
          command: |
            ansible-playbook -vvv -i inventory/aws_ec2.yaml ./playbooks/health_check.yaml

  terraform_provision_load_balancer:
    executor: terraform
    working_directory: ~/project/terraform
    parameters:
      environment:
        type: string
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Terraform Version
          command: |
            terraform --version
      - run:
          name: Terraform Init
          command: |
            terraform init
      - run:
          name: Terraform Plan
          command: |
            terraform plan -var-file="vars/<< parameters.environment >>.tfvars" -var='enable_elb=true' -out << parameters.environment >>.tfplan
      - run:
          name: Terraform Apply
          command: |
            terraform apply << parameters.environment >>.tfplan

workflows:
  deploy:
    jobs:
      # - terraform_provision_ec2:
      #     context:
      #       - aws_deploy
      #     environment: development

      - ansible_playbook:
          context:
            - aws_deploy
          # requires:
          #   - terraform_provision_ec2

      # - terraform_provision_load_balancer:
      #     context:
      #       - aws_deploy
      #     requires:
      #       - ansible_playbook
      #     environment: development