---
# tasks file for elixir_release

name: Release Elixir Application
block:
  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Print service facts
    ansible.builtin.debug:
      var: ansible_facts.services