# An Ansible playbook is like a set of instructions or a
# "recipe" for automating tasks on computers. It tells
# Ansible what to do, step by step, such as installing
# specific versions of software, configuring settings
# such as environment variables, or updating systems.
- name: Setup Health App
  hosts: group_olympus_backend
  vars:
    app_name: health_check
  roles:
    - deploy_health_check
